### ISSUE TITLE
Use Gradle Extension

### ISSUE THREAD

**Issue by willis7** [ferigma/dbunit-gradle-plugin#1]
A Gradle extension allows the user to define a configuration block which can then be used by tasks to avoid duplication of property definitions.

Something like:

```
dbunit {
  driver
  username
  password
  url
  schema
  dataTypeFactoryName = DEFAULT_DATA_TYPE_FACTORY_NAME
  supportBatchStatement = false
  useQualifiedTableNames = false
  datatypeWarning = false
  escapePattern
  skipOracleRecycleBinTables = false
  skip = false
  metadataHandlerName = DEFAULT_METADA_HANDLER_NAME
  caseSensitiveTableNames = false
}
```

Using convention mapping the user should be able to override these properties in a lazy way, so that if they choose to have multiple tasks of the same type, each task can use its own values.

**Comment by ferigma** [comment]
Hi Sion,

This is a great idea! I already merged your PR to the master!

Even though I have no paid so much attention lately to this plugin, I appreciate very much you collaboration. I hope we can collaborate many more times :)

Cheers

**Comment by willis7** [comment]
My pleasure, this is a great plugin :+1:
